### ISSUE TITLE
No Background Image

### ISSUE THREAD

**Issue by toni-z** [tgcowell/waves#49]
Since the last months i don't have the background image. Only a blue color.

**Comment by ezankel** [comment]
Also having this issue after updating to the latest version of Home assistant on RPi 3

**Comment by tgcowell** [comment]
Hi All,

Can you please refer to the instructions on main page? HACS made some changes that requires a new location be made.

Thanks

**Comment by toni-z** [comment]
Thanks. Now everything works

**Comment by Boerny41** [comment]
Hi,

I've got the same problem and must admit that I don't understand the instructions. To me, they don't make any sense:

1. "Create the following folder: /config/www/waves/" **Done** 

2. "Download the images located within the themes folder, everything excluding waves.yaml" **Done** though I don't know why.

3. "Reload or Restart Home Assistant, your theme should now include the backgrounds and animated images." **Done** but nothing changed since I never uploaded the images anywhere. I tried putting them in `/config/www/waves/` but it didn't help.

What exactly am I missing?
